# Generated by Django 4.2.4 on 2023-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.TextField(max_length=25)),
                ('familiya', models.TextField(max_length=25)),
                ('sinf', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.TextField(max_length=25)),
                ('familiya', models.TextField(max_length=25)),
                ('fan', models.TextField()),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
